# For more information: https://laravel.com/docs/sail
name: 'text2img-geneartor'
services:
    web:
        image: 'php83-cli'
        build: 
            context: './docker'
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
                WWWUSER: '${WWWUSER:-1000}'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/usr/src/myapp'
        command: ['php', 'artisan', 'serve', '--port=80', '--host=0.0.0.0']
